#!/usr/bin/with-contenv bash
set -Eeuo pipefail
request=/var/lib/cage/state/shutdown-request
while true; do
  if [[ -f "$request" ]]; then
    rm -f "$request"
    kill -TERM 1
    exit 0
  fi
  sleep 0.2
done
